# Fuente
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Cursor
cursor_shape block
cursor_blink_interval 0.5

# Mouse
mouse_hide_wait 0
url_color #0087bd
url_style curly

# Ventana
remember_window_size  yes
initial_window_width  1200
initial_window_height 700
window_padding_width 8
hide_window_decorations yes
confirm_os_window_close 0

# Pestañas
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Tema - Dracula (modo oscuro)
foreground #f8f8f2
background #282a36
selection_foreground #ffffff
selection_background #44475a

# Negro
color0  #21222c
color8  #6272a4

# Rojo
color1  #ff5555
color9  #ff6e6e

# Verde
color2  #50fa7b
color10 #69ff94

# Amarillo
color3  #f1fa8c
color11 #ffffa5

# Azul
color4  #bd93f9
color12 #d6acff

# Magenta
color5  #ff79c6
color13 #ff92df

# Cyan
color6  #8be9fd
color14 #a4ffff

# Blanco
color7  #f8f8f2
color15 #ffffff

# Opacidad
background_opacity 0.95

# Atajos de teclado
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
